# Generated by Django 3.0.2 on 2020-01-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('capacity', models.IntegerField()),
                ('web_lecture_support', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[('OVL', 'Oval'), ('REC', 'Rectangle'), ('CAN', 'Canopy'), ('ELE', 'Elevated')], max_length=3)),
            ],
        ),
    ]
