# Generated by Django 3.0.2 on 2020-01-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='web_lecture_support',
            field=models.BooleanField(default=True),
        ),
    ]
