# Generated by Django 3.0.2 on 2020-01-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doj', models.DateField(auto_now_add=True)),
                ('salary', models.IntegerField()),
                ('subjects', models.ManyToManyField(to='subjects.Subject')),
            ],
        ),
    ]
