# Generated by Django 3.0.2 on 2020-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_takes_web_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='doj',
            field=models.DateField(),
        ),
    ]
