# Generated by Django 3.0.2 on 2020-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20200127_1110'),
        ('teachers', '0003_auto_20200127_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='subjects.Subject'),
        ),
    ]
