# Generated by Django 3.0.2 on 2020-01-27 06:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('chapters', models.IntegerField()),
                ('total_duration', models.IntegerField()),
                ('per_class_duration', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(300)])),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='classrooms.ClassRoom')),
            ],
        ),
    ]
