# Generated by Django 3.0.2 on 2020-01-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20200127_0800'),
        ('subjects', '0002_auto_20200127_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to='classrooms.ClassRoom'),
        ),
    ]
